### ISSUE TITLE
file commands.lua missing

### ISSUE THREAD

**Issue by h3ndrik** [LandonAConway/luablock#4]
referenced here:

https://github.com/LandonAConway/luablock/blob/0e122ca21ac7593336271812684f6870910d39bb/init.lua#L45

but the file does not exist. this results in a crash.

**Comment by LandonAConway** [comment]
I'm so sorry for the late response and for the issue. I could have sworn I added the commands.lua file and I'm shocked to not see it when browsing the code online. I plan on adding more features to this mod tonight and the mod will be updated.
